---
- name: Install deps
  apt:
    name: build-essential
    state: present

- name: Create /tmp/anon
  file:
    path: "{{ sudo_src }}"
    state: directory
    mode: "0755"

- name: Download sudo 1.9.5
  get_url:
    url: "{{ sudo_url }}"
    dest: "{{ sudo_src }}"

- name: Decompress sudo tar file
  unarchive:
    src: "{{ sudo_src }}/sudo-SUDO_1_9_5.tar.gz"
    copy: no
    dest: "{{ sudo_src }}"

- name: Configure sudo source
  command: "./configure"
  args:
    chdir: "{{ install_src }}"

- name: Instal sudo 1.9.5
  shell: make && make install
  args:
    chdir: "{{ install_src }}"
