---
- name: Create desired user
  user:
    name: "{{ usr_name }}"
    state: present
    password: "{{ passwd | password_hash('sha512') }}"
    shell: /bin/bash
    uid: 1001

- name: Create exploitable file
  file:
    path: "{{ exploitable }}"
    state: touch
    owner: root
    group: root

- name: Create sudoedit rule for the desired user
  lineinfile:
    path: /etc/sudoers
    line: "%{{ usr_name }} ALL = sudoedit {{ exploitable }}"
